version: '2'

plugins:
  eslint:
    enabled: true
    channel: 'eslint-7'
    config:
      config: '.eslintrc.json'
      extensions:
        - '.ts'
        - '.tsx'
checks:
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 250

exclude_patterns:
  - '**/node_modules/**'
  - '**/test/**'
  - '**/*.spec.ts'
  - '**/*.test.ts'
  - '**/*.spec.tsx'
  - '**/*.test.tsx'
  - '**/*.d.ts'
