name: Gated CI
on:

  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '**/LICENSE'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/.gitignore'
      - '**/LICENSE'


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

  lint:
    name: Lint and TypeCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint

      - name: TypeCheck
        run: yarn tc

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      # - name: Test
      #   run: yarn test --coverage

      - name: Test & Coverage
        uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_COVERAGE_TOKEN }}
        with:
          debug: true
          coverageCommand: yarn test --coverage



